#+title: Notas de Sistemas Operativos
#+date: <2026-08-11 Tue>

* Primera Clase
** Objetivo

Ver problemas vinculados con sistemas operativos. Entender cómo funcionan.
Cómo funcionan por detrás de la interfaz. Pasan muchas cosas, algunas buenas,
otras malas. El sistema operativo tiene que lidiar con todas ellas.

** Definición

Software que funciona como intermediación entre el Hardware y el usuario, sea
humano o entidad automatizada.

Sirve de intérprete entre usuario y la máquina.

Es un software distinto al resto, con cuatro características que lo distinguen.

Se ejecuta solo al momento de arrancar la computadora.

** Núcleo

El sistema carga el núcleo. Es un software extremandamente simple, chico y
fácil. El resto de componentes no forma parte del sistema operativo. Es el
revoque.

Hay sistemas operativos que tienen /micronúcleo/ y sistemas operativos con
núcleos monolíticos.

** Módulo I

Tenemos una introducción, que profundiza en lo que hablamos. Además tenemos
otro apunte y un video corto para revisar. Por último, tenemos dos trabajos
prácticos. El primero es sobre la evolución de los sistemas operativos y el
segundo WebOS, sobre sistemas operativos web.

Con respecto a los sistemas Web, vamos a investigar qué son, cuáles están
vigentes, si se utilizan, expectativas a futuro, características de cada uno.
Hay que buscar 5. Nombre, creador, características, si sige vigente o no.

Para la siguiente clase. Trabajar el apunte, ver el video, resolver los
prácticos. Se entregan en 15 días.

*** TODO Trabajar el apunte

*** TODO Revisar apuntes y ver el video de nuevo

*** TODO Hacer el práctico I

*** TODO Hacer el práctico II

** Condiciones de aprobación

Dos parciales aprobados. Todos los TP entregados.

Los parciales tienen dos partes. Una teórica y otra práctica. Tenemos
multiple-choice capciosos y análisis de situaciones prácticas, donde tenemos
que argumentar con lenguaje técnico y preciso.

** Notas Video Sistemas Operativos

Historia. En los 40 y principios de los 50. Las computadoras ocupaban habitaciones
enteras y ejecutaban un programa a la vez. Se programaba con tarjetas perforadas
y la máquina podía estar días procesando.

A medida que las computadoras crecen en rendimiento, el tiempo humano comenzó a ser el cuello de botella.
Por eso nace el procesamiento por lotes.

Las computadoras, además de crecer en pode de cómputo, bajan de precio e incorporan
dispositivos periféricos, que requieren de controaldores.

A fines de los 50, las computadoras podían ejecutar varias programas a la vez,
aprovechando los tiempos muertos, como, por ejemplo, cuando se envía un trabajo a imprimir.
Este concepto se denomina *multitarea*.

*Gestión de Memoria*. Ejecutar muchos programas requiere maneter memoria para cada uno.
Se empieza a asignar espacios de memoria para cada programa. Cuando los programas
requieren de mayor memoria, el sistema les entrega bloques de memorias separados.
El problema de este sistema es que no se puede conocer bien la ubicación de la memoria.
Para ello se desarrolla el concepto de *memoria virtual*. Cada programa tiene su
memoria asignada. Si un programa falla, no puede afectar a otros programas.
Además, aparece la protección de memoria, que impide que un programa lea la memoria
asignada a otros.

En los años 70, una misma computadora podía atender varias terminales. Para ello,
se desarrollan los sistemas operativos de tiempo compartido. En ese momento nace
Multics, sistema operativo de tiempo compartido. En ese contexto nace Unix,
con un núcleo simple y herramientas separadas, con programas y bibliotecas.
Con el tiempo, aparecieron compiladores y editores de texto para el sistema,
lo que lo convirtió en el sistema más popular.

En los años 80, las computadoras continuaron bajando sus precios, convirtiéndose
en equipos hogareños.

En la actualidad, los sistemas operativos están en nuestros equipos, teléfonos,
televisores. Hoy en día, son muy resilientes, fallan rara vez.
