= Zar, 10 de septiembre 2026
Dan <ise.daniel@gmail.com>
v0.1 2026-09-15

.Objetivos
- Tomamos nota
- Vemos qué mira el zar
- Me preparo para cuando no esté
- Para hacer mis propios análisis de coyuntura

.Complicada
- Complicada. Medio Oriente no se calma. La tasa no baja. Argy no va al
  mercado.
- Hay que aguantar con las reservas que tenemos.

.Reserva Federal
- Es importante aunque tenga una verdulería.
- Confiar porque sino no hay confianza.
- Japón: vuela por los aires.
- El chiste es ver lo global para entender junto con lo local. Darle bola
  también a lo global te permite hacer la diferencia porque no muchos le dan
bola aquí.

.Geopolítica
- El zar se puede equivocar. Pero el consume y trae.
- Idea: si no se resuelve de un día para el otro, tipo Venezuela, tenemos
  disrupción en el mercado de la energía. Porque la estrategia de Irán para
resistir es aguantar presionando el mercado de petróleo global.
- Trump: energía más alta es malo para las elecciones. Entonces, su objetivo es
  cerrar lo más rápido que pueda. En USA: "Galón por encima de 4USD, pierdes la
elección".
- Uno pensaría que el conflicto se resuelve rápido.
- Hay otra lectura. Gordos geopolítica. Idea: USA necesita conflicto duradero.
  Para complicar a su principal rival: China. 20 puntos de su abastecimiento
energía viene del Golfo. En Venezuela se saca 1M barriles. Y se pierden 20M del
Golfo. En concreto: barril en 100 USD.

.Reserva Federal
- Los Bancos Centrales van con _forward guidance_: no quieren sorpresas.
  Preanuncian lo que van a hacer. _Teoría maradoniana de la tasa de interés_.
Pero el _Mudo_ Warsh juega a no decir.
- Esto perjudica a Argy. Con tasas para arriba, endeudarse en el mercado
  internacional es imposible. Hay que ver en 3 meses qué pasa.
- El mercado de bonos es aburrido. Pero es mucho más grande que las acciones.
  Entonces: *hay que mirar el mercado aburrido*.
- El Tesoro americano se está endeudando de corto para comprar de largo. No son
  volúmenes relevantes. Pero USA tiene un problema estructural. Todos los
bancos están levantando tasas. No van a financiar al tesoro. Yen se deprecia.
La normalización del mercado de Japón no alcanza. USA no quiere Japón
depreciado.  Por eso le compra Yenes. No lo dice. _Teoría Maradoniana_. Parece
que interviene y confirma. Déficit creciendo. El mercado viene comprando
títulos.  Pero no sigue a 4%. Japón también vende. Hay sobreoferta.
- Esta semana _meeting_. Definen tasa a un día.

.Argy
- Pasa lo de siempre. Primer semestre todo bien: mejor estacionalidad por
  nuestras exportaciones. Además subió el precio de nuestra nueva exportación:
petróleo.
- *Años de estabilidad*: aburridos. Son para planificar. Argy nos da un respiro
  para que nos acomodemos y nos preparemos para sobrevivir a lo que viene.
- *Estacionalidad del mercado de cambios*. Dicen: ya no es más estacional.
- Teníamos muchas regulaciones cambiarias. Bajaba salida y entrada, bajaba
  flujo. Queda un mercado muy abocado a lo comercial: no se puede entrar, no se
puede salir: crece el peso de lo comercial: los granos.
- El *Zar*: es verdad, pero *sigue siendo estacional*. Primer semestre sobra,
  segundo falta. Es cierto que el primero estás _muy_ sobrado. Las compras de
la primera parte no van a pasar en la segunda. Por eso el BCRA se mete de a
poco. Comprar 10M por día es _muy_ positivo. Puede pasar que no compre. Es lo
que se esperaba.
- El BCRA comprando pone _piso_ al dólar. Si no hubiesen comprado sería más
  bajo. El ancla no puede ser el dólar si están comprando.
- Dentro de ese contexto: los *últimos meses*, *dejan de poner piso y pisan*.
  Por el _cambio de estacionalidad_ de la que hablamos. Se le puso techo 
devolviendo. Vende _$LELINK_ que indexa por oficial. Se lleva pesos con eso y
_sube_ la tasa.
- Pero: la *volatilidad* es mala. Hace que los actores retrasen decisiones, se
  comporten defensivos. Eso no implica fijar a cualquier precio. Un precio 
creíble permite anclar expectativas. Y dejar que se mueva un poco puede anclar.

.Actividad
- Mayo más o menos. Junio mejor. Julio el peor dato. Industria y construcción
  un desastre. 
- *Gobierno*: si la economía hace piso, necesita que sea ahora. Pero los datos
  de empleo siguen siendo malos. _Lo positivo:_ el mercado no mira 2027. Cuando
mire 2027 se va a poner volátil. Hay que tratar que la economía se recupere en 
este trimestre. Hoy está peor. No camina lo que mueve el trabajo en núcleos
urbanos. Todavía "hay tiempo". Si no se recupera este último trimestre, se 
puede volver loco el mercado. Octubre, elecciones en Brasil. Si gana Lula, 
corrección del Real.
- *Inflación*. Sigue en torno a 2%. La baja es errática e inercial. Va a seguir
  así. La volatilidad de precios es alta: es difícil elegir sectores para sacar
_outlier_ porque cualquier sector se dispara un mes y baja al siguiente.

.Crédito y Mora
- *2024*. Boom de crédito. Muchos componentes. General: excepcional.
  Condiciones complejas, de repago dudodas. Telón de fondo: se entra en
estancamiento. Por lo tanto, lógico el crecimiento de la mora. Mucho crédito se
tomó pensando en licuación. Se ajustan los ingresos, se complica el mercado de
trabajo y crece la mora. 
- Además, la volatilidad de tasa pre-electoral hizo que bajen los préstamos. Se
  recobra la mora con los que ya existen. También presiona sobre el medido de
la mora.
- El lío está en préstamos de familias. Pagando mínimo de tarjeta de crédito.
- El boom de crédito se hizo a 80% TNA. Tasas reales del 40% anual. La deuda
  crece más rápido que el ingreso. 
- El préstamo se pacta fijo. Pero si el ingreso disponible se afina, es
  esperable que no se priorice el pago del préstamo.
- No llega a ser un problema sistémico, tipo crisis sub-prime.
- Si el telón de fondo se recompone, debería recomponerse la mora. Es decir,
  depende de la actividad. Si el gobierno no recupera la actividad, se va a
complicar.
- Mora: si el moroso empieza a pagar, aunque esté en refinanciamiento, tiene
  que garpar 5 meses. I.e., la estadística no va a bajar rápidamente.
- *No es un problema entre privados*. Los bancos centrales velan por la
  estabilidad del sistema financiero. Porque el Estado es el regulador del
sistema financiero y lo tiene que cuidar. Es rol del Banco Central.
- El presidente del Banco Central tiene que cuidar su comunicación. Se analiza
  la carta orgánica del banco central en el próximo episodio. La independencia
se construye respetando la carta orgánica. Por lo tanto, no puede twittear así.
Ni hacer comunicados conjuntos con el Tesoro.

