= Zar, 17 de septiembre 2026
Dan <ise.daniel@gmail.com>
v0.1 2026-09-17

.Objetivos
- Tomamos nota
- Vemos qué mira el zar
- Me preparo para cuando no esté
- Para hacer mis propios análisis de coyuntura

.Conflicto Medio Oriente
- WTI es precio de intermediación en Texas. El que tendríamos que mirar es el
  Brent. Para Argentina y para nuestro análisis. Fondo de Petróleo de EEUU en
mínimos.
- Oleoducto de Arabia Saudita roto. Permitía desviar parte de Ormuz al Mar
  Rojo. Frenada por un mes. Huties controlan Bab al-Mandeb. Esto afecta a
Europa.
- Presiona sobre el precio del petróleo. Sobre la *inflación* en EEUU.

.Conferencia Kevin Warsh, el _Mudo_ 
- El zar es fenomenal, él le puso el apodo del Mudo.
- Warsh está haciendo lo que dijo que iba a hacer. No hay sorpresa. Está
  haciendo lo que el Zar quería que haga Powell. Dijo algo importante: la
economía está sólida y la inflación sigue por arriba. Por lo tanto, hay que
preocuparse por la inflación. El sesgo tiene que estar sobre inflación. La
única manera de tener pleno empleo en el largo plazo es bajar la inflación. No
es sostenible el pleno empleo con estos niveles de inflación. Por lo tanto: se
apunta todo a inflación. Aparentemente una suba más este año y se queda ahí
para 2027. 
- *Esta tasa no es restrictiva*, porque sigue creciendo la economía y no se
  cumple la meta de inflación. Hay que bajar inflación más rápido.
- Ser mudo está bien para ser banquero central. Bausili tendría que aprender.
- Warsh: no creo en el _forward guidance_, el mercado tiene que trabajar con la
  información que hay. La decisión del Banco Central se basa en los datos de la
realidad. Los tomadores de decisión tienen que atender a esos datos de la
realidad. Los inversores deben asumir un riesgo que estén dispuestos a asumir,
en lugar de confiar en el _guidance_ del Banco Central. Esto incrementaría la
disciplina del mercado y evitaría la toma excesiva de riesgos.
- La _suba_ fue votada unánime. La FED es presidencialista.
- El mercado se hizo bolsa sobre el final de la rueda pero después devolvió.
  Por lo tanto: Al *mercado hay que darle tiempo*. No hay que interpretar en
tiempo real.

.Argy
- Presenta un presupuesto con superávit fiscal. Pero no hay buena reacción. En
  primer lugar, porque no hay superávit financiero. Porque no se contabiliza el
pago de intereses de la deuda. Se ha cumplido con la disciplina fiscal. No se
miran ya los datos fiscales. Todos dan por hecho la discplina fiscal. Positivo
porque ancla espectativas. El frente fiscal se deterioró. La recaudación bajó. 
Lo fiscal está fino. En el estado de situación del país, el superávit no
resuelve.
- Problemas Argy: mercado laboral. El desempleo sigue relativamente bajo,
  aunque subió. La crisis de Macri fue de desempleo de dos dígitos. El
desempleo sigue subiendo. A la par sube la informalidad. Es decir, también hay
deterioro en lo cualitativo. Hay un problema tendencial: hasta cuando la
economía crece, crece el empleo informal.
- Este modelo necesita *estabilidad* para funcionar. Una devaluación no
  resuelve los problemas. El mensaje es: al populismo se lo combate con
ortodoxia. 
- Energía crece, minería crece. Pero se necesita *estabilidad política*, porque
  esos sectores tienen una maduración de muchos años. Esto puede generar un
flujo de dólares que permita tener estabilidad cambiaria.
- El BCRA compra 5 por día. Flojo. En el primer semestre se ganó. Ahora toca
  aguantar. Como Estudiantes.
- El Gobierno da bola a la tasa. Quieren que reactive el crédito. Toleran un
  dólar más alto con tal de tener *estabilidad de tasa*. Vencían 8 y el Tesoro
renovó 8. No tomó la sobreoferta. Significa que va haber más oferta de pesos.
- Calipso es el sistema de gestión que necesitás.

.Carta Orgánica BCRA
- Tiene media en diputados. Salió sin cambios de la comisión del Senado.
- Es la ley que regula al Banco Central. 
- La dirección es la correcta. Pero no hay ley que cambie la cultura
  institucional argentina. En cuanto sea necesario, se usarán sus grises.
- Discusión internacional: cuál es el mandato. En general, la estabilidad de la
  moneda. No tienen nada vinculado a actividad o empleo. Pero todos los bancos
la miran. Todos se preocupan por la estabilidad monetaria, el empleo y la
estabilidad financiera. Pero lo hace en el marco de un objetivo de inflación.
Argy tiene que dar un mensaje de que va a ser _hawkish_.
- Se fortalece al directorio. Esto está bien. Perú y NZ funciona así. Los
  gobiernos se tienen que acostumbrar a lidiar con su presidente del Banco
Central.
- El Banco Central _debería_ beneficiar sectores.
- No va a poder financiar al tesoro, no puede comprar títulos. Se eliminan los
  adelantos transitorios. La emisión tiene dos mecanismos: adelantos
transitorios y ganancias contables. Se transfieren al tesoro. En la práctica, se

QUEDO: 56M

