= Zar, 10 de septiembre 2026
Dan <ise.daniel@gmail.com>
v0.1 2026-09-15

.Objetivos
- Tomamos nota
- Vemos qué mira el zar
- Me preparo para cuando no esté
- Para hacer mis propios análisis de coyuntura

.Complicada
- Complicada. Medio Oriente no se calma. La tasa no baja. Argy no va al
  mercado.
- Hay que aguantar con las reservas que tenemos.

.Reserva Federal
- Es importante aunque tenga una verdulería.
- Confiar porque sino no hay confianza.
- Japón: vuela por los aires.
- El chiste es ver lo global para entender junto con lo local. Darle bola
  también a lo global te permite hacer la diferencia porque no muchos le dan
bola aquí.

.Geopolítica
- El zar se puede equivocar. Pero el consume y trae.
- Idea: si no se resuelve de un día para el otro, tipo Venezuela, tenemos
  disrupción en el mercado de la energía. Porque la estrategia de Irán para
resistir es aguantar presionando el mercado de petróleo global.
- Trump: energía más alta es malo para las elecciones. Entonces, su objetivo es
  cerrar lo más rápido que pueda. En USA: "Galón por encima de 4USD, pierdes la
elección".
- Uno pensaría que el conflicto se resuelve rápido.
- Hay otra lectura. Gordos geopolítica. Idea: USA necesita conflicto duradero.
  Para complicar a su principal rival: China. 20 puntos de su abastecimiento
energía viene del Golfo. En Venezuela se saca 1M barriles. Y se pierden 20M del
Golfo. En concreto: barril en 100 USD.

.Reserva Federal
- Los Bancos Centrales van con _forward guidance_: no quieren sorpresas.
  Preanuncian lo que van a hacer. _Teoría maradoniana de la tasa de interés_.
Pero el _Mudo_ Warsh juega a no decir.
- Esto perjudica a Argy. Con tasas para arriba, endeudarse en el mercado
  internacional es imposible. Hay que ver en 3 meses qué pasa.
- El mercado de bonos es aburrido. Pero es mucho más grande que las acciones.
  Entonces: *hay que mirar el mercado aburrido*.
- El Tesoro americano se está endeudando de corto para comprar de largo. No son
  volúmenes relevantes. Pero USA tiene un problema estructural. Todos los
bancos están levantando tasas. No van a financiar al tesoro. Yen se deprecia.
La normalización del mercado de Japón no alcanza. USA no quiere Japón
depreciado.  Por eso le compra Yenes. No lo dice. _Teoría Maradoniana_. Parece
que interviene y confirma. Déficit creciendo. El mercado viene comprando
títulos.  Pero no sigue a 4%. Japón también vende. Hay sobreoferta.
- Esta semana _meeting_. Definen tasa a un día.

.Argy
- Pasa lo de siempre. Primer semestre todo bien: mejor estacionalidad por
  nuestras exportaciones. Además subió el precio de nuestra nueva exportación:
petróleo.
- *Años de estabilidad*: aburridos. Son para planificar. Argy nos da un respiro
  para que nos acomodemos y nos preparemos para sobrevivir a lo que viene.
- *Estacionalidad del mercado de cambios*. Dicen: ya no es más estacional.
- Teníamos muchas regulaciones cambiarias. Bajaba salida y entrada, bajaba
  flujo. Queda un mercado muy abocado a lo comercial: no se puede entrar, no se
puede salir: crece el peso de lo comercial: los granos.
- El Zar: es verdad, pero sigue siendo estacional. Primer semestre sobra,
  segundo falta. Es cierto que el primero estás _muy_ sobrado. Las compras de
la primera parte no van a pasar en la segunda.

QUEDO EN: 31M
