= Notas sobre Economía en 3 minutos
Dan <ise.daniel@gmail.com>
v0.1, 2026-09-15

La idea es tomar nota y dejar emerger lo más importante para el análisis. Poder
construir una plantilla con la cual hacer mi propio análisis de coyuntura. Para
eso vamos a tomar nota del Colo, del Parte Diario y del Zar. Vemos qué termina
saliendo.

Buenas y malas.

Las buenas. Inflación en línea. Inflación núcleo igual a julio. Estacionales
deflación. 

Las malas. Actividad Julio. Construcción e Industria (INDEC) peor a lo
esperado. No tenemos agosto, pero no viene mejor. Faena caída fuerte. Inversión
es retener stock.

Financiero. Buena licitación de bonos, con rollover superior al 100,
contractivo en liquidez.

Dólar tranquilo. Flujo para comprar va a haber. Petroleras emiten bonos. San
Juan también.

Política. Oposición ingresa proyectos. Los políticos se guían por encuestas.
Con gobierno débil van a pedir más.

Esta semana: costo de construcción, inflación mayorista, datos PBI segundo
trimestre, desempleo (venía 7.8%), balance comercial agosto, número fiscales.
Reunión de la FED. Encuestas Brasil.

*Observaciones.* 
- Seguir publicaciones INDEC, que emerjan los patrones.
- Seguir licitaciones de Bonos.

