= Notas de Clase, Sistemas Operativos
Dan <ise.daniel@gmail.com>
v 0.6, 2026-09-22

.TODO 
. Revisar clases y trabajar las notas
- Quedo 17M, 25-ago
. Resumir los apuntes


== Primera clase, 11 de agosto

.Objetivo de la materia
Ver problemas vinculados a los sistemas operativos. 
Entender cómo funcionan por detrás de la interfaz. 
En el _backend_ pasan muchas cosas, buenas y no tanto. 
El sistema operativo tiene que lidiar con todas ellas.

Se van a presentar distintos sistemas operativos.
Lo importante es conocer que no se agota en los más conocidos: Windows, Linux,
MacOS o Android.

Veremos las cosas que tienen todos en común.

.Definición de sistema operativo
Software que se ocupa de la intermediación entre el Hardware y el Usuario, sea
humano o entidad automatizada.

Sirve de intérprete entre usuario y máquina.

Es un software distinto al resto, con cuatro características que lo distinguen.

. Tiene su propio *sistema de archivos*.
El sistema operativo puede administrar las cosas que trabajamos y guardamos.
Los sistemas pueden generar archivos, pero no decidir dónde guardarlos.
Es un sistema de organización de la información.
. Tiene un *intérprete de comandos*.
Es una interfaz, en la que puedo escribir instrucciones y ejecutar comandos.
Para algunos casos de uso puede ser mejor que la interfaz gráfica.
. Tiene un *núcleo*, también llamado *kernel*.
Cada sistema operativo tiene su propio kernel.
. Se *ejecuta a sí mismo* al momento de arrancar la computadora.
No necesita del usuario para comenzar a funcionar.
La carga se hace con una _rutina de booteo_.

Hoy en día hay electrodomésticos con sistemas operativos.
Que, por ejemplo en televisores, permiten conectarse a internet y acceder a 
servicios orientados a ellos.

.Rutina de _booteo_
El sistema carga en memoria su núcleo.
Lo demás no es parte del núcleo, sobre él se ejecuta el resto de cosas.
El resto de componentes no forma parte del sistema operativo. 
El sistema operativo es el _motor_ del auto.

Algunos tienen _micronúcleo_. Otros, como Linux, núcleo _monolítico_.
Cada uno tiene sus ventajas y desventajas.


=== Notas Video Sistemas Operativos

.Historia
40 y principios de los 50. 
Las computadoras ocupaban habitaciones enteras. 
Ejecutaban un programa a la vez, que podía durar días. 
Se programaba con tarjetas perforadas.

A medida que crece el poder de cómputo, el tiempo humano comenzó a ser el cuello
de botella.
Por eso nace el *procesamiento por lotes*.

Además de crecer en poder de cómputo, bajan de precio e incorporan dispositivos
periféricos, que requieren de controladores.

A fines de los 50, las computadoras podían ejecutar varias programas a la vez,
aprovechando los tiempos muertos, como, por ejemplo, cuando se envía un trabajo
a imprimir. Este concepto se denomina *multitarea*.

.Gestión de Memoria
Ejecutar muchos programas requiere mantener memoria para cada uno.  
A cada uno se le asigna su espacio.
Cuando requieren de más memoria, se les entrega bloques separados.
Pero los programas no pueden gestionar por sí solos la memoria física.
Por eso nace el concepto de *Memoria virtual*.
Cada programa cuenta con su memoria asignada.
Si un programa llegara a fallar, no puede afectar a los demás.

Emerge además el concepto de *protección de memoria*.
Que implica que un programa no puede leer la memoria asignada a otro.

En los 70s, una misma computadora podía atender varias terminales. 
Por ello se desarrollan los *sistemas operativos de tiempo compartido*.
Nace Multics. 
Y luego Unix, con un núcleo simple y herramientas separadas, con programas y
bibliotecas.  
Con el tiempo, aparecen compiladores y editores de texto para el sistema, lo que
lo convirtió en el más popular.

En los 80s, las computadoras siguienron bajando sus precios, convirtiéndose en
equipos hogareños.

En la actualidad, los sistemas operativos están en nuestros equipos, teléfonos,
televisores. 
Son muy resilientes, fallan rara vez.


== Segunda clase, 18 de agosto

Tema de hoy: procesos e hilos.
Concepto usado por el sistema operativo para la organización y ejecución del 
trabajo.

.Proceso 
Es una instancia de un programa en ejecución. 
Tiene su propio espacio de memoria aislado del resto.
En él se guardan el código y los datos.
Cuenta además con recursos asignados.
Tales como archivos abiertos, conexiones de red, identificadores de sistema. 
El sistema usa un número, el _Process ID_, para identificarlo.

Cuando la máquina arranca se ejecutan muchos procesos de forma automática.
Por ejemplo, el antivirus Windows Defender.

.Hilo
Es una unidad de ejecución dentro de un proceso.
Los hilos de un mismo proceso comparten el espacio de memoria.
Código, datos y _heap_ son comunes.
Solo la pila es propia de cada hilo.

Crear un hilo es más liviano.
Cuesta menos tiempo y memoria que crear un proceso.

Hay riesgo de _condiciones de carrera_. 
Tema que veremos más adelante, es un problema de _sincronización de procesos.

Ejemplo, el autoguardado de Word.
Se ejecuta con independencia del usuario.
La detección de nuestro _input_.
Dónde estamos haciendo click, qué teclas tocamos.
Cada uno es un hilo.

Se puede pensar al proceso como una casa.
Los hilos serían como una familia, que comparte la casa.

.Procesos vs. Hilos
[cols="1,2,2"]
|===
|Aspecto |Proceso |Hilo

|Memoria 
|Espacio propio, aislado del resto
|Compartida entre Hilos del mismo proceso 

|Costo de creación 
|Alto
|Bajo

|Comunicación
|Requiere IPC (_buffers, pipes, sockets_)
|Directa: comparten el mismo espacio de memoria 

|Aislamiento
|Alto: un fallo en un proceso no afecta al resto 
|Bajo: un hilo puede afectar a los otros
|===

=== Por qué son importantes

La elección entre procesos e hilos depende de las prioridades.

.Aislamiento y robustez
Si se requiere resiliencia frente a fallos, convienen procesos separados.

.Eficiencia y comunicación
Para tareas relacionadas, que requieren acceder a los mismo datos de forma 
rápida, convienen los hilos.

.El _Scheduler_ decide
El sistema operativo reparte procesos e hilos entre los núcleos de la CPU.

Ejemplo.
Tengo dos instancias de Excel.
Hago doble click en un archivo y trabajo en él.
Luego hago doble click en otro archivo.
Tengo dos procesos.
Cada uno tiene su propia memoria.
Cada uno tiene su propio `PID`.
Cada instancia tiene su hilo para la interfaz y su hilo para el cálculo, por 
ejemplo.
Si una de las instancias se cae, la otra no se ve afectada.

En Ingeniería de Software es fundamental elegir correctamente nuestra
arquitectura para aprovechar los conceptos de *Procesos* e *Hilos* de acuerdo
a las _necesidades_.

=== Estados de los Procesos

El *estado* de un proceso se define por la actividad en que se encuentra.
Pueden ser 5:

. Nuevo, _New_: cuando el proceso es creado, pero todavía no se ejecuta.
. Listo, _ready_: listo para ejecución, a espera de tiempo de procesador.
. En ejecución, _running_: cuando procesado asignado y ejecuta instrucciones.
. Bloqueado, _waiting_: a la espera de un evento, v. g., de entrada/salida.
. Finalizado, _terminated_: finalizó ejecución.

.Esquema de transiciones de estado

=== Preguntas

.¿La carga del Kernel es un proceso?
Sí, de por sí es un proceso.

.¿Un comando es un hilo?
Un comando interno, interior al kernel, es un hilo del kernel.
Un comando externo, como `tree`, es un proceso independiente.

.¿Qué pasa con los hilos cuando termina un proceso?
Se terminan.
Porque están dentro del proceso.

Esto sucede en Windows.
Pero no sucede en Linux.
Existe el concepto de *proceso zombie*.
El proceso murió pero el hilo sigue.
Porque maneja de una forma distinta.

=== Concurrencia

.Problemas clásicos de concurrencia
Es un problema que emerge cuando dos procesos quieren acceder, al mismo tiempo,
al mismo recurso.
Hay tres tipos de problemas de concurrencia.

. Problemas de lectores y escritores
. Problemas de productores y consumidores

.Problemas de lectores y escritores
Se da cuando más de un proceso quiere acceder para escribir al mismo recurso.
Se resuelve impidiendo que dos procesos escriban sobre el mismo recurso al 
mismo tiempo.

Cuando un proceso solicita permiso de _escritura_ sobre un recurso, el sistema
operativo impide que cualquier otro proceso escriba sobre él.

.Problemas de productores y consumidores
Hay procesos que generan datos para que los utilicen otros. 
Un proceso es *productor*: genera datos.
Otro es *consumidor*: toma esos datos.
Este problema requiere de *servicios* para que los procesos se _comuniquen_ y 
_sincronicen_.

.Mutex
Semáforo de dos colores.
Habilita (o no) la ejecución de un proceso.

Para algunas situaciones no alcanza un semáforo de dos luces.
Porque se despedicia tiempo.
Ese otro sistema se conoce como _variable condicional_.

.Variable condicional
Es un mutex pero de tres luces.
La variable condicional tiene los mismo dos, pero incorpora _wait_ y _signal_.
Implica _pasar con cuidado_.
No es complicado de implementar.

.Deadlock, o _exclusión mutua_ 
Dos procesos llegan al mismo tiempo al mismo recurso.
Como cuando dos autos quieren pasar por un punte de una sola mano.
Se encuentran por la mitad.
_Qué hacemos_.
Es sencillo: uno lo tiramos al río.

Así se resuelve un _deadlock_: se mata uno de los dos procesos.
Se lo termina y se lo vuelve a ejecutar desde el principio.
El usuario no lo nota.
Esto sería Windows.

Linux es distinto.
Tiene la instrucción `kill` para elegir el proceso a matar.
Cualquier sistema operativo moderno tiene que lidiar con estos problemas.


== Tercera clase, 25 de agosto

Mac es caro.
Pero muy bien diseñado.
Enfocado en usabilidad.

Linux es gratis.
Pero muchos consideran que es difícil.
Como cuando surgió DOS.

En el medio tenemos Windows.
No tan difícil.
Pero no gratis.

=== Transiciones

Vimos que los procesos podían tener diferentes estados.
Cuando cambia de estado decimos que hace una *transición* de procesos.

Hay cuatro transiciones posibles.
Cada una tiene un nombre, dado por una letra.

.Transición A
Cuando un programa necesita un elemento para continuar (dato, señal, etc.).
El proceso se encuentra a la espera de que un _evento_ ocurra.

Como cuando un sistema pide una contraseña al usuario y aguarda que la ingrese.

.Transición B
Cuando el programa ha utilizado un tiempo asignado de procesador y tiene que
dejar el paso al siguiente proceso. 
El sistema frena ese proceso y deja que otro continue.
Es lo que haría el _mutex_ cuando bloquea un proceso.

El sistema asigna tiempo de ejecución a cada proceso.
Si no termina, lo frena y le da paso a otro.

.Transición C
El proceso se encuentra _preparado_ y pasa a _ejecución_.

.Transición D
Cuando pasa de _bloqueado_ a _preparado_.

.Cambio de contexto
Cuando se pasa de una transición a otra hablamos de un _cambio de contexto_. 
Puede ser _parcial_ (entre hilos del mismo proceso) o _completo_ (cambio de
procesos, hilos de distintos procesos).

=== Planificación

El sistema tiene un proceso interno que se llama _Planificador_ (_Scheduler?_).

Los diferentes estados tienen una relación directa con las _prioridades_. 

La planificación se puede hacer de tres formas posibles:

. A largo plazo
. A mediano plazo
. A corto plazo

=== Algoritmos de planificación 

Hay dos tipos de algoritmos de planificación y todo sistema aplica los dos,
dependiendo de lo que necesite.

.Round-Robin
Rotativamente asigna tiempos de ejecución a distintos procesos.  
Se conoce también como algoritmo de rueda, porque se puede visualizar como una.
El orden de asignación es secuencial y siempre igual.
Los procesos que terminan de ejecutarse salen del anillo. 
Los que todavía siguen en ejecución permanencen en él.

.FIFO o FCFS (First Come First Serve)
