
* Primera clase

Fecha: 16/3/26

** Origenes de un sistema

Puede ser por una *necesidad* de un cliente.

O hago un sistema y la necesidad del mismo surge por sus características.

** Etapa: Entrevista

Primera entrevista con el cliente, tomamos un cafe,
escuchamos la idea. Todo se cobra.

Iteramos informes hasta que el cliente esté conforme.
El cliente tiene que dar su conformidad porque tiene que haber un compromiso.

Todo informe es un *resguardo legal* para nosotros.
El primero no es el más importante.
Los siguientes son más importantes.
Pero es un primer resguardo.
Hay documentación avalando el trabajo a hacer.

En esta instancia todavía no se puede hablar de requerimientos.
Solo tenemos una /idea muy vaga/ de lo que el cliente quiere.

** Un sistema siempre existe

Un sistema es un conjunto de cosas que actúan coordenadamente para
lograr un objetivo, cada una con un objetivo particular.

Ese sistema se puede reflejar en el sistema informático.

** Etapa: Relevamiento de información

Pasamos a la siguiente etapa, ya con un informe preliminar hecho y firmado.

Tenemos *entrevistas* con las personas que /ya hacen funcionar al sistema/.
Nos tenemos que entrevistar con todos.

Otra posibilidad es hacer una *observación* in situ.
Por lo general, suele poner nerviosa a la gente.
No suele ser, por ende, una buena estrategia.

También se puede hacer una *encuesta*,
pidiendo opinión de cada persona involucrada.

Podemos recurrir a un *muestreo*,
que se usa cuando el número de personas haciendo algo es muy grande.
Elijo un subgrupo, me entrevisto con ese subgrupo y punto.

Para el muestreo: elijo al /más antiguo/, al /más nuevo/ y a uno del /medio/.

Cada uno va a tener distintas ideas y pueden ser útiles para diseñar el sistema.

** A la hora de la entrevista

Primero me /presento/, porque sino no van a decir nada.

Tomamos notas /lápiz y papel/, porque si grabamos *nadie nunca va a hablar nada*,

Esto tiene que ver con el primer punto, que apunta a /ganar confianza/.

A cada persona le vamos a preguntar por /documentos/, /papeles/,
cosas que utilicen en su trabajo.
Pedimos copias de esa documentación, porque el sistema va a tener que
generar esa documentación en el futuro.

Con todo este laburo hecho, tenemos los *requerimientos*.
Después de hacer mucho trabajo.

** Requerimientos

Se dividen en dos ramas:
- funcionales
- no funcionales

Un *requerimiento funcional* es una función que el sistema *tiene* que cumplir.
Son aquellas cosas que /tenemos que programar/, sea la interfaz,
ingreso a base de datos. Todo lo que /necesitamos programar/.

Un *requerimiento no funcional* no necesita ser programado, tiene que ver con el
/entorno del sistema/. Por ejemplo, en un cajero automático,
ingreso una tarjeta y me pide una clave. Ese pedido de clave
lo tengo que programar.
Que el cajero esté disponible las 24hs es un requerimiento no funcional,
porque no necesito programarlo. Tiene que ver con el Hardware.

Un sistema que envia una boleta por Whatsapp cumple con un requerimiento no
funcional, porque eso no lo programo yo (hasta cierto punto).

Entonces,
tenemos los *informes*, requerimientos *funcionales*, *no funcionales*.
Le mostramos esto al cliente, el cliente /lo firma/.

** Cobrar

Vamos cobrando por etapas.
Cobramos la entrevista,
cobramos el relevamiento.
Aunque no hayamos /hecho nada/ aun.

(Igual, depende).

** Etapa: Análisis

Análisis de factibilidad, hacemos uno para el cliente,
y uno para nosotros.

Analizamos:
*** Factibilidad técnica
que computadora tiene el cliente, que sistema operativo tiene,
si tiene que comprar computadoras nuevas o no.

Analizamos *nuestra factibilidad*, ¿tenemos /nosotros/ la computadora
para desarrollar el sistema que tenemos que desarrollar?

*** Factibilidad operativa
Que recursos humanos tiene el cliente, lo puede manejar al sistema,
hay que capacitar al personal.

Lo mismo de nuestra parte, ¿tenemos los recursos humanos para encarar
este proyecto? ¿Tenemos que formar recursos?

*** Factibilidad económica
¿El cliente tiene los recursos para pagarnos?
¿Tenemos nosotros los recursos para encarar este proyecto?

*** Informe: estudio de factibilidad 

De ahi sale el informe, el *estudio de factibilidad*,
con el diagrama de *Pert/Gantt*.

La persona me hace tres preguntas inmediatamente:
¿Cuánto me va a costar?
¿Cuánto tiempo vas a tardar?
¿Cuánto tiempo voy a tardar en recuperar la inversión?

Una cosa muy piola que hay que hacer es siempre
/estimar de más/. Si yo se que demoro siete meses,
al cliente le digo nueve meses.

Lo mismo los costos:
vamos arriba, vale USD 40.000.
Si después gastamos menos, le hacemos un descuento y va a estar contento.
Pero si le aumentamos se va a enojar.

** Etapa: diseño global

Recién aqui empezamos a diseñar el sistema.

Hacemos el primer diseño en papel.

En el papel hacemos un

*** Diagrama de flujo de datos

Gráfico que representa a todo el sistema,
sus partes,
como se van a comunicar,
graficamos como se mueven los datos por el sistema que se va a construir.

*** Diagrama de entidad relación

Es el diseño de la base de datos, ni más ni menos.
Una vez diseñada, la optimizamos,
que sea rápida, se guarden correctamente.


*** Normalización

Para eso existe la *normalización*,
reglas para simplificar y optimizar la base de datos.

*** Orientado a objetos

Si tenemos un diseño orientado a objetos, lo armamos en el
CU/HU.

Una vez hecho todo esto se lo pasa al programador.

Todo esto vamos a hacer, salvo programar en adelante.

** Programación, pruebas, mantenimiento, desmantelamiento

Estas son las etapas que siguen del ciclo de vida del software, 
pero no vamos a trabajar con estas etapas en esta materia.

