#+title: Notas de Clase, Programación Avanzada 2
#+date: <2026-08-13 Thu>

* Temas y Condiciones
** Temas
Vamos a ver tecnologías web, tanto Frontend como Backend.

** Condiciones de Aprobación
Las usuales en el resto de materias. Además tenemos un trabajo práctico grupal.
Grupos de 4 o 5 miembros.

* Primera Clase
** HTML
Hasta ahora vimos un lenguaje de Backend (C#) y programamos servicios web con
Entity Framework.

Cada plataforma tiene tecnologías asociadas. MacOS tiene la suya, etc. Todos
tienen en común (incluyendo un televisor y otros) un *stack HTML*. Por eso el
/Frontend HTML-CSS-Javascript/ nos permite alcanzar a la mayor cantidad de
clientes y plataformas posibles.

** Historia
Surge en los 80. Su objetivo era compartir docuemntos científicos. Está basado
en SGML. Básicamente consiste en definir la estructura de un documento con
etiquetas.

HTML significa HyperText Markup Language. Lenguaje de Etiquetado de HiperTexto.

** Hipertexto
Concepto anterior a HTML. Define un documento cuyos conceptos están vinculados
entre sí, más allá del propio texto. Es decir, más allá del uso usual de
conectores.

El idioma provee conectores para relacionar conceptos en el texto. El hipertexto
prevé el concepto de /enlace/ para relacionar conceptos entre si.

** Etiquetas
El uso de etiquetas como ~<title>~ permite definir elementos. Se basan en SGML,
pero incorpora el concepto de Hipertexto, con los enlaces.

Vienen generalmente en pares, como ~<p>hola mundo!</p>~. La primera es una
*etiqueta de apertura*. Entre las etiquetas tenemos el *contenido*. Y al final
tenemos una *etiqueta de cierre*. En el ejemplo se define un *elemento p* o
párrafo.

Algunas etiquetas son auto-cerradas, como la etiqueta de imágen: ~<img/>~.

** HTML5
Es el último estándar definido. No se esperan nuevas versiones, sino
modificaciones a esta última versión. Por lo que se prefiere usar directamente
la nomenclatura HTML.

** Lenguaje de Marcado
No es un lenguaje de programación. No permite definir lógica, flujo de
ejecución, definición de comportamiento. Es un lenguaje /presentacional/. Se
encarga de la estructura formal de un documento.

Su potencial radica en la difusión del *stack HTML*, presente en computadoras,
dispositivos smart, consolas de videojuegos, etc.

** Documento HTML
Es un conjunto de etiquetas y contenido asociado. Por ejemplo:

#+begin_src html
<!DOCTYPE html>
<html>
    <head>
      <title>Documento</title>
    </head>
    <body>
      <p>hola mundo!</p>
    </body>
</html>
#+end_src

Podemos abrir un archivo de texto plano con el navegador. Y el navegador va a
tratar de renderizarlo de la mejor manera que pueda. Pero quedaría al criterio
de cada navegador. Para mejorar tanto la experiencia de nuestros usuarios, como
nuestro puntaje en un índice de un buscador, conviene cumplir con buenas
prácticas.

En primer lugar, debemos empezar con ~<!DOCTYPE html>~, de acuerdo con el
estándar HTML5. Luego, todo documento tiene que comenzar con las etiquetas
~<html>~. Todo el resto de etiquetas serán /subelementos/ o /elementos hijos/ de
esta etiqueta.

Dentro de la etiqueta ~<head>~, la etiqueta del /encabezado/, tenemos las
etiquetas referidos a los /metadatos/ del documento, como por ejemplo la
etiqueta de título ~<title>~, o la etiqueta del encoding de nuestro documento
~<meta charset="UTF-8">~. Es información sobre nuestro documento que no será
renderizada, pero puede seer importante para nuestros usuarios o para los
buscadores.

** Comentarios en HTML
Se especifican con:

#+begin_src html
<!-- Esto es un comentario -->
#+end_src

** Elementos en línea y elementos en bloque
En HTML se pueden distinguir los elementos en dos grandes grupos:

- Elementos en línea: son aquellos elementos que /no/ terminan en una nueva
  línea. Por ejemplo: ~<span>~, ~<img>~, ~<a>~.
- Elementos en bloque: elementos que finalizan con un salto de línea, como:
  ~<p>~.

** Atributos de elementos HTML
Se escriben como pares clave-valor, dentro de las etiquetas. Por ejemplo:

#+begin_src html
<a href="www.google.com">Link</a>
#+end_src

Si un atributo es /booleano/, se puede indicar que es verdadero de cualquiera de las siguientes formas.

#+begin_src html
<input type="checkbox" checked>
<input type="checkbox" checked="">
<input type="checkbox" checked="checked">
#+end_src
