= Notas de Curso de CSS desde Cero
Dan <ise.daniel@gmail.com>
v 0.1, 2026-08-31

Aquí incluyo las notas del curso
https://www.youtube.com/playlist?list=PLUofhDIg_38q7l8gV4IVCz_pjUeyD99_j[CSS
desde Cero].

== CSS

Aparece en diciembre 1996. Con soporte primero en Explorer 3.  Es un lenguaje
declarativo, de marcado, para describir la presentación de un documento, en el
caso del desarrollo web, de un documento HTML. 

.W3C
Lo estandariza la *World Wide Web Consortium* (W3C).

.Cascada
**C**ascade **S**tyle **S**heet. Hojas de Estilos en Cascada. Hojas de Estilos 
refiere al conjunto de reglas a aplicar. Cascada refiere a que las reglas se 
aplican en un _orden específico_. Ese _orden_ depende de unas reglas. Y pueden 
implicar _sobreescritura_, es decir, unas reglas pueden sobreescribir otras de
acuerdo a unas reglas determinadas. Se profundiza abajo.

.Recursos recomendados
* Curso de CSS de Google en https://web.dev[web.dev]
* https://developer.mozilla.org[Mozilla Developer Network (MDN) Web Docs].

== Dónde se especifican los estilos

Hay tres formas.

.Etiqueta `<style>`
Suele ir dentro de `<head>`.
[source, html]
----
<style>
  /* Declaramos que los elementos h1 sean azules */
  h1 {
    color: rgba(21, 21, 230, 0.75);
  }
</style>
----

.Atributo `style` en una etiqueta
[source, html]
----
<h1 style="color: blue">Este título es azul.</h1>
----

== Selectores

.Elementos
Se pueden utilizar directamente los nombres de los elementos.

[source, css]
----
/* elegimos los anchors */
a {
  color: blue;
}
----

.Clases
Utilizamos un punto.

[source, css]
----
/* elegimos los elementos clase .azul */
.azul {
  color: blue;
}
----

.Id
Utilizamos el numeral. Hay que tratar de evitar ID para estilizar porque 
estaríamos repitiendo estilos.

[source, css]
----
/* elegimos el elemento de ID #azul */
#azul {
  color: blue;
}
----

Los selectores se pueden combinar, con un espacio de por medio. El primer 
elemento es el padre. El segundo el hijo.

[source, css]
----
/* elegimos el strong dentro de un párrafo.
 * aquí notamos que es una práctica interesante leer selectores de derecha a 
 * izquierda
 */
p strong {
  color: blue;
}
----

Hay que tener un poco de cuidado con estos selectores. Si tenemos elementos 
anidados las reglas se pueden aplicar dos veces. Ejemplo, el selector `ul li`
aplicado a:

[source, html]
----
<ul>
  <li>Elemento base</li>
    <ul>
      <li>Elemento anidado</li>
    </ul>
</ul>
----

Se puede usar `>` para aplicar solo a los hijos directos. Selecciona solo los 
elementos inmediatamente hijos del elemento de la izquierda. 

[source, css]
----
article > p {
  font-size: 16px;
}
----

`~` permite elegir los operadores que están después, pero a la vez son hermanos.
Es decir, hijos del mismo elemento. `+` es lo mismo, pero tienen que ser
hermanos directos. Tiene que venir _justo_ después.

== Herencia

Algunas propiedades se heredan. Por ejemplo, `font-family`. 

[source, css]
----
/* El resto de elementos del body va a heredar la font-family sans-serif */
body {
  font-family: sans-serif;
}

/* Por el concepto de cascada, sin embargo, podemos sobreescribir  */
h1 {
  font-family: monospace;
  border: 3px solid #09f;
}
----

.Formal Definition
En *MDN* tenemos la _Formal Definition_ de cada propiedad. En dicha sección 
encontramos:

- Valor inicial
- A qué elementos aplica
- Si *hereda* o no
- Valor computado
- Tipo de animación

Además de muchos otros aspectos, como la sintaxis, ejemplos.

== Pseudoclases

Los elementos tienen _estados_. Por ejemplo, cuando ponemos el cursor por encima
de un elemento, está en estado de _hover_. Con esto podemos incorporar cierta 
interactividad a la interfaz. Que reaccione a cambios en el estado.

[source, css]
----
/* seleccionamos los anchor cuando el curso está por encima */
a:hover {
  /* ... */
  outline: 3px solid rgb(231, 57, 57);
}
----

En las herramientas de desarrollo se pueden _checkear_. Por ejemplo, simular el
`:hover` para testear.

== Cascada

Uno de los conceptos más importantes. Refiere al sistema de sobre-escritura de 
estilos. Frente a dos declaraciones, cuál es la que prevalece. Todo CSS se basa
en este principio. Puesto que todo elemento tiene ya estilos por defecto. Lo que
hacemos es sobreescribir. 

.Especificidad
Es un concepto central para entender la cascada. CSS determina la
_especificidad_ para cada selector. El selector de mayor especificidad es el que
se termina aplicando. 

Es un cálculo de tres niveles. En la primera puntuación considera IDs. La
segunda clases, atributos y pseudo-clases. La tecera elementos y
pseudo-elementos. El primer nivel vale más que el segundo, y este más que el 
tercero (como en el medallero olímpico: 1 de oro vale más que 99 de plata). 

Cuando dos declaraciones tienen la _misma especificidad_, la que prevalece es la
que está _más abajo_.

[source, css]
----
p {
  color: #09f;
}

/* misma especificidad, este prevalece */
p {
  color: red;
}
----

La especificidad se puede ver en las *Herramientas de Desarrollo*.

Si usamos estilos _en línea_, directamente sobre los elementos HTML o
introducidos con JS, podemos saltarnos la especificidad. Aunque no es una
práctica recomendada, porque estaríamos rompiende la distribución de roles.

También puede saltarse con `!important`. Aunque si dos estilos tienen
`!important`, terminan desemptando por alguno de los otros criterios.

== Display

Tenemos en línea `inline` y tenemos en bloque `block`. Hay otros, pero esos son
los principales. En línea como el texto, en bloque como los títulos (agregan un
salto de línea, se apilan, en lugar de ponerse al costado como el texto).

.Box-sizing
Controla qué consideramos con `height` y `width`. Con `content-box`, el que 
viene por defecto, controlan el _content_. Con `box-sizing: border-box;` hacemos
que el `width` y el `height` determinen el tamaño desde el borde hacia adentro.

== Overflow

Por defecto, `overflow: visible;`. Tenemos otros:

. `hidden`: que no se vea. No se ve ni agrega scroll.
. `scroll`: no se ve, pero el navegador agrega barras de desplazamiento.
. `auto`: es como scroll, pero si no lo necesita no va a poner barras.
Generalmente, si queremos `scroll` usamos este.

La barra se puede estilar con herramientas como `Scrollbar Playground`.

Para texto podemos usar `text-overflow: ellipsis`, que agrega puntos
suspensivos. Por defecto es `text-overflow: clip;`.

== Position




[source, css]
----
/* Voy en video 2 Flex 16M */
----