= Módulo 6 - Análisis técnico
Dan <ise.daniel@gmail.com>
v 0.1, 2026-09-14
:stem:

Recta final del curso. 
Hoy https://x.com/CD_AnalisisTec[Cristian Díaz]. 
En la primera parte vemos la teoría, en la segunda la práctica. 
Nos llevamos las 3 o 4 cosas más importantes.

== Definición

El *Análisis Técnico* es el estudio de los movimientos del mercado usando
gráficos. 
Es una herramienta usada a nivel global, para todo tipo de activo. 
Aunque, en particular, renta variable y cripto.

Se trata de pronosticar la tendencia futura, para invertir a su favor.
Las probabilidades de éxito se maximizan yendo _con_ el mercado, no contra él.

Se basa en 3 premisas. 

. Los movimientos del precio descuentan todo
. Los precios se mueven por tendencias
. La historia se repite

== Los movimientos del precio descuentan todo

Cualquier dimensión que pueda afectar, sean políticas, fundamentos,
psicológicas, se reflejan en el precio.
Esos factores afectan oferta y demanda, es decir, el flujo.
Y el *flujo determina el precio*.
V. g.: un balance mejor al esperado, aumenta la demanda por encima de la oferta
y tenemos una suba.

Mediante el análisis del gráfico se busca la tendencia.

== Los precios se mueven por tendencias

Una tendencia suele continuar.
Por eso las indentificamos y operamos a favor.

== La historia se repite

Se identifican estructuras, asociadas con la _psicología humana_.
Los patrones se identificaron y clasificaron en el pasado.
Se asume que siguen funcionando a futuro.

== Teoría de Dow

Padre del análisis técnico.
Dio su nombre al índice Dow-Jones. 
Reconoce *3 tendencias*.

.Tendencia alcista
Si tenemos picos y valles crecientes.

.Tendencia bajista
Picos y valles descendentes.

.Pausa de tendencia
Picos y valles a misma altura.

A partir de las 3 tendencias se reconocen *3 fases de mercado*:

. Acumulación
. Participación pública
. Distribución

.Acumulación
Los inversores, generalmente institucionales, comprenden que las malas noticias
se han descontado.
Al no haber malas noticias, debería comenzar un nuevo ciclo.

Comienzan a llevar en ese nivel la oferta, tomando de los que, por el motivo que
fuera, liquidan.
Se nota por el poco flujo.
De a poco van llevando posiciones.
Generalmente en una pausa de tendencia.

.Participación pública
Se caracteriza por movimientos alcistas.
Se acaba el proceso lateral y el volumen bajo.
Se observa demanda, de minoristas e institucionales.
El precio muestra una tendencia alcista.
Mínimos y máximos crecientes. 

En esta fase las probailidades están a nuestro favor.
Los inversores notan que el ciclo ha cambiado.

.Distribución
Cuando no puede estar mejor.
Todo el mundo comprando.
Los astutos que compraron cuando estaba mal comienzan a liquidar.
De a poco y progresivamente.
Como son grandes los que van saliendo, tenemos una pausa en la tendencia de
nuevo.
Al precio le _cuesta subir_.

> Una tendencia está en vigor hasta que da señales definitivas de retroceso

== Lectura de un gráfico

[horizontal]
Vela:: Materialización de cada jornada
Eje vertical:: Precio
Eje horizontal:: Tiempo

Con pocas herramientas de análisis gráfico ya se puede trabajar. 

Las empresas del mismo sector se mueven de forma similar.

.Velas
Representa una jornada bursátil.
[horizontal]
Línea fina:: Mínimo y máximo
Cuerpo:: Apertura y cierre
Verde/roja:: Roja si el cierre es inferior, verde si el cierre es superior

Las velas tienen formas y cada una significa cosas distintas.
Por ejemplo, *vela martillo*.

== Tendencias

Indican la direción del mercado.
El mercado no se mueve de forma lineal, sino en _zig zag_.
Si estamos en una tendencia alcista, 
los movimientos bajistas se denominan *contratendenciales*.

Los movimientos no pueden ser lineales.
A medida que un activo sube, los inversores _toman ganancias_.
Generan así un movimiento contratendencial.
En el movimiento contratendencial se suben los nuevos jugadores.
Un movimiento lineal,
sin movimientos contratendenciales,
es una mala señal.
No es un activo muy operado.

== Soportes y resistencias

.Resistencia
Punto a partir del cual la oferta supera a la demanda y hace que el precio 
muestre una comportamiento a la baja.

.Soporte
Lo contrario.
A un precio, aparece la demanada, mostrando un comportamiento al alza.

.Revelancia
Resistencias y soportes son *mas relevantes* cuanto más contactos tenga el
precio donde haya reversión del comportamiento.

.Longitud
Resistencia con mayor duración es más relevante.

.Voúmen
Se agrandan las barras, indica mayor congestión.
Si en una resistencia tenemos crecimiento de volumen, hay muchos vendedores:
la resistencia es _difícil_ de superar.

.Números redondos
Inciden psicológicamente.

== Análisis de Gráficos

Vemos líneas de tendencias.
Se definen *validadas* cuando tienen 3 contactos o más precisos.
*Probables* cuando tienen menos de 3.
Las líneas validadas son las más útiles.
Un soporte alcista es un *soporte dinámico*,
que se mueve al alza.
Cuando el activo toque nuevamente el soporte dinámico,
uno tiende a pensar que es punto de reversión al alza,
por lo tanto, punto de entrada para el inversor.

El precio en que el activo quiebra el soporte, ponemos un _stop loss_.
Que implica liquidar la posición para evitar las pérdidas.

Una resistencia quebrada al alza puede servir como piso.

== Operación

Compro en el soporte.
Pongo stop-loss por debajo.
Vendo cuando reconoce la resistencia.

Las líneas se trazan en el extremo inferior de las velas
(el mínimo de la jornada).

.Operación de procesos laterales
No compramos cerca del nivel de resistencia.
Sería mala estrategia.
Si quiebra la resistencia es una señal de fortaleza.
Ahí compramos.

.Gaps
Cuando hay un gap entre un día y otro,
podemos trazar un soporte horizontal o estático.
Lo contrario ocurre con los gaps bajistas:
el gap marca una resistencia estática u horizontal.

== Patrones de cambio y continuidad de tendencia

.Hombro-cabeza-hombro
Una tendencia alcista alcanza un punto y luego quiebra a la baja.
Esta acción en tendencia alcista probablemente ha finalizado su ciclo.
(Pierde el soporte dinámico y el soporte estático de canal lateral).

.Patrón inferior triple
Lo mismo pero haciendo un valle.
A partir de ahí rompería al alza.

== Estudio de medias móviles

Una media móvil es el precio promedio de un período del pasado.
Por ejemplo, la media móvil de las últimas 10 ruedas.
La línea muestra el precio promedio.
Permite suavizar y definir tendencias.

.Permite definir compras y ventas
Si el precio pasa de arriba hacia abajo es venta.
Si el precio pasa de abajo hacia arriba es compra.

Pueden operar como resistencias o soportes dinámicos.
Cuando quiebra la media hacia arriba es compra.
Cuando quiebra la media a la baja es venta.
En ocasiones conviene entrar con el activo por encima de la media móvil y
acompañar el ascenso.

[source]
----
// 1H 15M
----