= Módulo 6 - Análisis técnico
Dan <ise.daniel@gmail.com>
v 0.1, 2026-09-14
:stem:

Recta final del curso. 
Hoy https://x.com/CD_AnalisisTec[Cristian Díaz]. 
En la primera parte vemos la teoría, en la segunda la práctica. 
Nos llevamos las 3 o 4 cosas más importantes.

== Definición

El *Análisis Técnico* es el estudio de los movimientos del mercado usando
gráficos. 
Es una herramienta usada a nivel global, para todo tipo de activo. 
Aunque, en particular, renta variable y cripto.

Se trata de pronosticar la tendencia futura, para invertir a su favor.
Las probabilidades de éxito se maximizan yendo _con_ el mercado, no contra él.

Se basa en 3 premisas. 

. Los movimientos del precio descuentan todo
. Los precios se mueven por tendencias
. La historia se repite

== Los movimientos del precio descuentan todo

Cualquier dimensión que pueda afectar, sean políticas, fundamentos,
psicológicas, se reflejan en el precio.
Esos factores afectan oferta y demanda, es decir, el flujo.
Y el *flujo determina el precio*.
V. g.: un balance mejor al esperado, aumenta la demanda por encima de la oferta
y tenemos una suba.

Mediante el análisis del gráfico se busca la tendencia.

== Los precios se mueven por tendencias

Una tendencia suele continuar.
Por eso las indentificamos y operamos a favor.

== La historia se repite

Se identifican estructuras, asociadas con la _psicología humana_.
Los patrones se identificaron y clasificaron en el pasado.
Se asume que siguen funcionando a futuro.

== Teoría de Dow

Padre del análisis técnico.
Dio su nombre al índice Dow-Jones. 
Reconoce *3 tendencias*.

.Tendencia alcista
Si tenemos picos y valles crecientes.

.Tendencia bajista
Picos y valles descendentes.

.Pausa de tendencia
Picos y valles a misma altura.

A partir de las 3 tendencias se reconocen *3 fases de mercado*:

. Acumulación
. Participación pública
. Distribución

.Acumulación
Los inversores, generalmente institucionales, comprenden que las malas noticias
se han descontado.
Al no haber malas noticias, debería comenzar un nuevo ciclo.

Comienzan a llevar en ese nivel la oferta, tomando de los que, por el motivo que
fuera, liquidan.
Se nota por el poco flujo.
De a poco van llevando posiciones.
Generalmente en una pausa de tendencia.

.Participación pública
Se caracteriza por movimientos alcistas.
Se acaba el proceso lateral y el volumen bajo.
Se observa demanda, de minoristas e institucionales.
El precio muestra una tendencia alcista.
Mínimos y máximos crecientes. 

En esta fase las probailidades están a nuestro favor.
Los inversores notan que el ciclo ha cambiado.

.Distribución
Cuando no puede estar mejor.
Todo el mundo comprando.
Los astutos que compraron cuando estaba mal comienzan a liquidar.
De a poco y progresivamente.
Como son grandes los que van saliendo, tenemos una pausa en la tendencia de
nuevo.
Al precio le _cuesta subir_.

> Una tendencia está en vigor hasta que da señales definitivas de retroceso

== Leer un gráfico

[horizontal]
Vela:: Materialización de cada jornada
Eje vertical:: Precio
Eje horizontal:: Tiempo

Con pocas herramientas de análisis gráfico ya se puede trabajar. 

Las empresas del mismo sector se mueven de forma similar.

.Velas
Representa una jornada bursátil.
[horizontal]
Línea fina:: Mínimo y máximo
Cuerpo:: Apertura y cierre
Verde/roja:: Roja si el cierre es inferior, verde si el cierre es superior

Las velas tienen formas y cada una significa cosas distintas.

== Tendencias

[source]
----
// 34M
----