= Notas de Parte diario, martes 15 de septiembre de 2026
Dan <ise.daniel@gmai.com>
v0.1, 2026-09-15

Mis notas sobre https://t.co/VshP1bdpMa[Parte Diario].

Semana complicada. 

Mercados:
- Asia a la baja
- Europa a la baja
- América a la baja. Bonos presionados, curvas _empinándose_. _Treasury_ a 10
  años en 5%, nivel más alto desde 2007. 
- Petróleo al alza

Observaciones: 
* Es decir, primero miramos los índices y materias primas.

Tres cosas a monitoreas:
. Reunión de la Reserva Federal. Ya se descuenta suba de 25 _basic points_. En
la última no subieron. 3 votaron suba. Ese número debe aumentar. Decisión
motivada por inflación. El Tesoro no está contribuyendo. Déficit fiscal alto.
Los "recortes" en personal son _migajas_ en relación al crecimiento del gasto.
3.5T.

. Medio Oriente. Huties atacaron nuevamente el oleoducto que devía la
exportación de petróleo fuera de Ormuz. Por eso reacciona el mercado de
petróleo. USA muestra poca capacidad para resolver.

. Teatro IA. Llamados a moderar el desarrollo, pero continuar IPO. Mercado no
lo toma seriamente. Goldman Sachs estima 5 del PBI global en IA.

Teatro en todos los frentes.

Observaciones: 
* Teatro no es exclusivo de Argentina. 
* Reserva Federal actor clave de la economía global.

