= Notas de Parte diario, 17 de septiembre de 2026
Dan <ise.daniel@gmai.com>
v0.1, 2026-09-17

Mis notas sobre Parte Diario, de Alberto Ades.

(Hoy tenemos audio. Por la reunión de la reserva de ayer).

.FED
- Suba de 25 _pbs_. Describe economía fuerte: Necesita tasas más altas durante
  más tiempo del que se pensaba.
- Comité espera 2% de crecimiento durante los próximos años.
- Espera 4.1% de desempleo.
- Ades: no está seguro de esta fortaleza de la economía. El mercado laboral
  muestra menor capacidad de creación de empleo. El desempleo sigue bajo y los
despidos no muestran señal de alarma. Pero la creación es baja y concentrada en
pocos sectores.
- Si FED tiene razón, mantener tasa alta tiene sentido. Sino no.
- Inflación sigue alta. 3.7%. Apunta a 2% en 2029.
- Espera mayor tasa por más tiempo, para llegar al 2%.
- Warsh: IA produciría grandes aumentos de productividad, actuando como fuerza
  desinflacionaria. No parece ser el caso en el corto plazo. Mitad del
crecimiento en la inversión se puede vincular a IA. (Hoy parece incrementar la
presión).
- Warsh: política monetaria no es restrictiva. Warsh no mencionó la tasa
  neutral. Criticó la práctica de dar orientación futura. Pero el comité si.
Para los mercados el sendero futuro es clave. (No tenerlo puede incrementar la
volatilidad). Sin embargo, el comité sigue revelando.

